### ISSUE TITLE
Bug Report: Issues of UI in displays below 390px width

### ISSUE THREAD

**Issue by alechaye** [livekit/components-js#664] opened 2023-10-23 05:26 UTC
### Select which package(s) are affected

\@livekit/components-styles, \@livekit/components-react

### Describe the bug

Livekit meeting creates a blank space in the right and bottom below 390px width devices. E.g. iPhone SE and S8+
<img width="407" alt="image" src="https://github.com/livekit/components-js/assets/106412628/f6e3ddd1-4da3-4805-a666-389ff02fed32">
<img width="550" alt="image" src="https://github.com/livekit/components-js/assets/106412628/9e584a90-fdd0-43f9-aa34-8bc69513e023">
Chat window overlaps the control bar on devices below 375px width. E.g. S8+. The control bar should extend fully from left to right as well as the chat window.
<img width="317" alt="image" src="https://github.com/livekit/components-js/assets/106412628/2fa74702-a48c-4d5e-a0e5-98d35be25b75">
<img width="520" alt="image" src="https://github.com/livekit/components-js/assets/106412628/6c1336e1-384b-4856-9517-7ce0158cf309">

### Reproduction

Use Chrome developer tools and look for iPhone SE and S8+

### Logs

```shell
Not needed
```

### System Info

```shell
Not needed
```

### Severity

annoyance

**Comment by lukasIO** [comment] 2023-10-23 10:45
Hi! 
I cannot reproduce any issues when selecting `iPhone SE`. It all looks fine there.
For `S8+` I'm not sure what's going on. The DPR value seems to messed up, but it only happens once a user visits the meeting page. So I'm not sure what we can do to circumvent that. It's also possible that this is an issue with the mobile device preview in chrome

<img width="787" alt="image" src="https://github.com/livekit/components-js/assets/12997837/c643324b-3ee6-42a3-b3cd-460fc39ab959">

**Comment by lukasIO** [comment] 2023-10-23 10:51
We would want to fix this on the meet level, I opened https://github.com/livekit-examples/meet/pull/142 for this

**Comment by alechaye** [comment] 2023-10-23 19:28
I took a look more closely, and it only happens in the Chrome developer tools. It does not happen in the Firefox developer edition developer tools. In order to reproduce it you have to zoom out. However, it seems that the width of the html and body element is right, and is highly likely this might not affect devices in production and might just be exclusive to the developer tools. However, might be worth taking a look into it. I have attached the screen recorded.


https://github.com/livekit/components-js/assets/106412628/7e2bf610-3c99-471d-90b5-9b32e59da944

**Comment by lukasIO** [comment] 2023-11-01 08:48
Agree with your assumptions. I'll close this for now, feel free to re-open if you notice that this is actually an issue on any real devices

**Closed by lukasIO** 2023-11-01 08:48 UTC
