### ISSUE TITLE
Connection quality indicator stuck at `unkown` when remote user enters room without publishing tracks

### ISSUE THREAD

**Issue by brkcrdk** [livekit/components-js#280] opened 2023-01-31 19:57 UTC
### Select which package(s) are affected

\@livekit/components-react

### What I'm expecting

I expect remote users correct value of connection quality level when remote user enters to room without publishing tracks.

### What happens instead

When remote user enters to room without publishing any track, connection quality indicator doesn't return correct value. When remote user starts to publishing a track then it started to returning correct value of connection quality. But for local user, it showed correct value without publishing track too.

### Reproduction

```js
function ParticipantConnectionQuality() {
  const { colors } = useTheme();
  const participant = useParticipantContext();
  const { quality } = useConnectionQualityIndicator({ participant });

  const qualityColors = {
    excellent: colors.primary,
    good: colors.warning,
    poor: colors.danger,
    unknown: colors.grayScale.gray700,
  };

  return (
    <ConnectionQualityIndicator
      participant={participant}
      style={{ color: qualityColors[quality] }}
    />
  );
}
```

### System Info

```shell
-
```

### Severity

annoyance

**Comment by lukasIO** [comment] 2023-02-01 16:05
thanks for the report!
this is currently by design on the LiveKit server side: updates will only be sent for participants you are currently subscribed to. 
Can I ask about your specific use case of why this would be useful to you?

**Comment by brkcrdk** [comment] 2023-02-01 16:17
Oh, understood. :)

Actually this is not lethal bug for me to be honest. I just noticed it yesterday. I am using `ParticipantLoop` and as a child component i use my custom `ParticipantTile` component . I just wanted to display connection levels. It is quite useful to have this feature if participant has admin role. That seemed odd to me and i thought it's a bug and i thought let you guys know. :D

But i also noticed that, if user publishes track once after entering to room this behaviour fixes. I think i am gonna do some quick toggle when entering to room if user muted everything.

**Comment by brkcrdk** [comment] 2023-02-02 18:25
Hey @lukasIO,

I just want to let you know about that i have just sort of fixed my problem by hiding indicator if user doesn't shares any kind of track at all. So this seems more reasonable then before to me. Because i think if a user isn't sharing any kind of track to the room it doesn't matter to me that how it's connection quality it's going to be and it doesn't affect other users quality either. 

What do you think about it?

```js
if (!isCameraEnabled && !isMicrophoneEnabled && !isScreenShareEnabled) return null;
if (quality === ConnectionQuality.Unknown) return null;
 ```

**Comment by lukasIO** [comment] 2023-02-03 11:42
hi @brkcrdk 
that sounds like a solid workaround!

I will close this issue for now as the current behavior is the intended one.

**Closed by lukasIO** 2023-02-03 11:42 UTC
