### ISSUE TITLE
Screenshare indicator isn't accuate

### ISSUE THREAD

**Issue by p-delorme** [livekit/components-js#532] opened 2023-06-26 16:02 UTC
### Select which package(s) are affected

\@livekit/components-react

### What is expected
If a user starts sharing his screen and then ends his screen sharing, the screenshare indicator should update with the proper state.

### Currently happening
Once a user starts a screenshare, even if he ends his screenshare, the indicator never changes

### Reproduction

Have 2 participants in a room and test the screensharing feature.

### System Info

```shell
JS-SDK
```

### Severity

annoyance

**Comment by Ocupe** [comment] 2023-06-27 08:46
Hey @p-delorme, thank you for your report. I'm afraid I don't fully understand your problem.
What do you mean by screen share indicator? Can you share some code on how you use it?
Could you elaborate a bit to help me understand?

**Comment by lukasIO** [comment] 2023-06-27 16:11
Sorry, I asked @p-delorme to open this issue, but forgot to give more context: 
The issue is around the `<TrackMutedIndicator source="screen_share" />` not updating correctly once the screen share has stopped via the browser UI.

**Comment by lukasIO** [comment] 2023-07-07 10:45
turns out this was likely a regression caused by a bug in client-sdk-js. @p-delorme can you check if the issue is indeed fixed for you, too with livekit-client@1.12.0 ?

**Comment by lukasIO** [comment] 2023-07-18 10:14
will close this, @p-delorme feel free to notify if this isn't fixed for you

**Closed by lukasIO** 2023-07-18 10:14 UTC
Labels: bug
